router bgp 200
  bgp router-id 100.100.2.1
  no bgp ebgp-requires-policy

  neighbor 8.2.2.2 remote-as 300
  neighbor 8.2.2.2 weight 100
  neighbor 8.2.2.3 remote-as 400

  address-family ipv4 unicast
  	network 8.1.2.1/24
  exit-address-family
