router bgp 300
  bgp router-id 100.100.3.1
  no bgp ebgp-requires-policy

  neighbor 8.2.1.1 remote-as 100
  neighbor 8.2.2.1 remote-as 200

  address-family ipv4 unicast
  	network 8.2.1.0/24
    network 8.2.2.0/24
  exit-address-family
